require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe StockLevelAdjustmentsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # StockLevelAdjustment. As you add validations to StockLevelAdjustment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # StockLevelAdjustmentsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all stock_level_adjustments as @stock_level_adjustments" do
      stock_level_adjustment = StockLevelAdjustment.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:stock_level_adjustments)).to eq([stock_level_adjustment])
    end
  end

  describe "GET #show" do
    it "assigns the requested stock_level_adjustment as @stock_level_adjustment" do
      stock_level_adjustment = StockLevelAdjustment.create! valid_attributes
      get :show, {:id => stock_level_adjustment.to_param}, valid_session
      expect(assigns(:stock_level_adjustment)).to eq(stock_level_adjustment)
    end
  end

  describe "GET #new" do
    it "assigns a new stock_level_adjustment as @stock_level_adjustment" do
      get :new, {}, valid_session
      expect(assigns(:stock_level_adjustment)).to be_a_new(StockLevelAdjustment)
    end
  end

  describe "GET #edit" do
    it "assigns the requested stock_level_adjustment as @stock_level_adjustment" do
      stock_level_adjustment = StockLevelAdjustment.create! valid_attributes
      get :edit, {:id => stock_level_adjustment.to_param}, valid_session
      expect(assigns(:stock_level_adjustment)).to eq(stock_level_adjustment)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new StockLevelAdjustment" do
        expect {
          post :create, {:stock_level_adjustment => valid_attributes}, valid_session
        }.to change(StockLevelAdjustment, :count).by(1)
      end

      it "assigns a newly created stock_level_adjustment as @stock_level_adjustment" do
        post :create, {:stock_level_adjustment => valid_attributes}, valid_session
        expect(assigns(:stock_level_adjustment)).to be_a(StockLevelAdjustment)
        expect(assigns(:stock_level_adjustment)).to be_persisted
      end

      it "redirects to the created stock_level_adjustment" do
        post :create, {:stock_level_adjustment => valid_attributes}, valid_session
        expect(response).to redirect_to(StockLevelAdjustment.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved stock_level_adjustment as @stock_level_adjustment" do
        post :create, {:stock_level_adjustment => invalid_attributes}, valid_session
        expect(assigns(:stock_level_adjustment)).to be_a_new(StockLevelAdjustment)
      end

      it "re-renders the 'new' template" do
        post :create, {:stock_level_adjustment => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested stock_level_adjustment" do
        stock_level_adjustment = StockLevelAdjustment.create! valid_attributes
        put :update, {:id => stock_level_adjustment.to_param, :stock_level_adjustment => new_attributes}, valid_session
        stock_level_adjustment.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested stock_level_adjustment as @stock_level_adjustment" do
        stock_level_adjustment = StockLevelAdjustment.create! valid_attributes
        put :update, {:id => stock_level_adjustment.to_param, :stock_level_adjustment => valid_attributes}, valid_session
        expect(assigns(:stock_level_adjustment)).to eq(stock_level_adjustment)
      end

      it "redirects to the stock_level_adjustment" do
        stock_level_adjustment = StockLevelAdjustment.create! valid_attributes
        put :update, {:id => stock_level_adjustment.to_param, :stock_level_adjustment => valid_attributes}, valid_session
        expect(response).to redirect_to(stock_level_adjustment)
      end
    end

    context "with invalid params" do
      it "assigns the stock_level_adjustment as @stock_level_adjustment" do
        stock_level_adjustment = StockLevelAdjustment.create! valid_attributes
        put :update, {:id => stock_level_adjustment.to_param, :stock_level_adjustment => invalid_attributes}, valid_session
        expect(assigns(:stock_level_adjustment)).to eq(stock_level_adjustment)
      end

      it "re-renders the 'edit' template" do
        stock_level_adjustment = StockLevelAdjustment.create! valid_attributes
        put :update, {:id => stock_level_adjustment.to_param, :stock_level_adjustment => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested stock_level_adjustment" do
      stock_level_adjustment = StockLevelAdjustment.create! valid_attributes
      expect {
        delete :destroy, {:id => stock_level_adjustment.to_param}, valid_session
      }.to change(StockLevelAdjustment, :count).by(-1)
    end

    it "redirects to the stock_level_adjustments list" do
      stock_level_adjustment = StockLevelAdjustment.create! valid_attributes
      delete :destroy, {:id => stock_level_adjustment.to_param}, valid_session
      expect(response).to redirect_to(stock_level_adjustments_url)
    end
  end

end
